### PR TITLE
feat: add DataTable component

### PR DESCRIPTION
**Pull request by Mohammer5**
This is the main PR for the DataTable component.

* Design PR: dhis2/design-system#7

## Workflow

I'd suggest we
* collect ToDos here (checkbox list)
* create separate PRs for those ToDos
* rebase-merge them onto this PR's branch

This way we can collaborate properly. If all parties agree, we can work in a BDD fashion, which means: We create the specs & test-code first, then write actual code. The tests will be added with PRs, so we're forced to think about the API and functionality properly and - once specs have been finalized - every participating devs knows what the component will/should look like.

<hr />

## ToDos

- [x] Align workflow (Done)
- [x] Create design (Done; @cooper-joe)
- [ ] Create spec files (In progress; @cooper-joe)
- [ ] Create component api (define prop types)
- [ ] ...

<hr />

## Tech-stack considerations

* [tannerlinsley/react-table](tannerlinsley/react-table)

### CODE REVIEW

**Comment by amcgee** [comment]
@Mohammer5 sounds great to me!

**Comment by cooper-joe** [comment]
Yes, this way of working sounds good to me. 👍 

My progress on the component design/spec
- [Done] First design drafts for all functionality
- [WIP] HTML&CSS mockup, used to deliver styling specs for all included styles/components
- [WIP] .feature files for all interactions and functionality, used to deliver all interactive specs

**Comment by cooper-joe** [comment]
Update: Here is a HTML&CSS mockup of each of the different table types described in the design system. The mockups use `ui-core` components. Please excuse my dodgy React skills. The HTML&CSS is intended to demonstrate the intended styling, not the intended markup. Please use it for the design specs only.
[Mockup full view](https://bvf5r.csb.app/)
[Mockup editor](https://codesandbox.io/s/table-styles-bvf5r)

**Comment by Mohammer5** [comment]
> Please excuse my dodgy React skills.

Don't worry about that, it's awesome you can do this!

**Comment by ismay** [comment]
So I heard from @Mohammer5 that once we've finalized the specs we can start work on this. I wouldn't mind helping out as this component is also needed before I can continue work on the scheduler-app. If there's anything I can do to help out let me know!

**Comment by edoardo** [comment]
Any ETA on when this is going to be implemented?
I'm waiting for it for the new "favorites" dialog (which could probably be a `ui-widget`?)

**Comment by Mohammer5** [comment]
@cooper-joe has recently worked on the specs and designs. I don't know if they've been finalized yet, but I guess we could start with the component soon, especially as 2.35 will take a while.

I'm "relatively busy" with the `Transfer` component right now, I think @HendrikThePendric is busy with the positioning stuff. Maybe @ismay, @Birkbjo or @varl ?

**Comment by varl** [comment]
Closing this based on comment in https://jira.dhis2.org/browse/TECH-215.

This will be implemented in the dhis2/ui monorepo that supersedes this repo.

**Pull request closed without merging**
