### PR TITLE
fix(headerbar): links and app icons

### LINKED ISSUE #8: HeaderBar: App icons are not loaded correctly
We're trying out the new HeaderBar with the app-runtime and we get some styling issues and missing icons in the app menu.

image

### PR DESCRIPTION
**Pull request by teug91**
* Fixes #8 
* Fixes various header bar links

There is a lot of `contextPath` prop-drilling. Do you prefer another implementation? Using `useContext` perhaps?

Also, maybe the locale stuff can be moved into the `useEffect`?

### CODE REVIEW

**Comment by amcgee** [comment]
Hi @teug91 thank you for this PR!  Are you using this version of the HeaderBar with `<DataProvider>` in a custom DHIS2 apps?

I've been wanting to update the links and icon paths here to support 3rd party domain deployments and non-core apps for a while.  I think we will want to use Context rather than prop-drilling, as you say.  I'll be extending the API of [dhis2/app-runtime](https://github.com/dhis2/app-runtime) shortly with a new hook to access application configuration (especially the `baseUrl`).  We currently have that information available in the `DataProvider` context but we don't expose the raw context to consumers.

I'll let @varl make the call on whether to accept this as-is and then update it to use context, or to wait for the new context accessor (probably next week).

**Comment by teug91** [comment]
Yes, I'm using this version along with `<DataProvider>` in custom apps. Everything seems to be working as expected apart from link and icon paths.

It makes no difference to me if we have to wait for context or if the PR is accepted. Thanks.

**Comment by varl** [comment]
>I'll let @varl make the call on whether to accept this as-is and then update it to use context, or to wait for the new context accessor (probably next week).

If it will be available this week, I think we should use the context. If it's going to take longer, merge this.

**Comment by varl** [comment]
It's been almost a month, so I'm going to go ahead and merge this for now, and we can refactor down the line. This doesn't touch the external component API, so refactoring to Context down the line is a non-breaking change. 

Thanks for this, @teug91.

**Comment by amcgee** [comment]
@varl OK sounds good.  For reference: This is the app-runtime change to enable context-provided application config https://github.com/dhis2/app-runtime/pull/13

**Pull request merged**
